// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/scania-setup/IndustrialTerminal.tsx": () => import("../components/mockups/scania-setup/IndustrialTerminal.tsx"),
  "./components/mockups/scania-setup/PasoAPaso.tsx": () => import("../components/mockups/scania-setup/PasoAPaso.tsx"),
  "./components/mockups/scania-setup/PickYourself.tsx": () => import("../components/mockups/scania-setup/PickYourself.tsx"),
  "./components/mockups/scania-setup/VerificationGate.tsx": () => import("../components/mockups/scania-setup/VerificationGate.tsx")
};
